version: '3.9'
services:
  db:
    image: postgis/postgis:15-3.3
    container_name: geolocations-db
    restart: always
    environment:
      POSTGRES_DB: geolocations
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: postgres
    ports:
      - "5432:5432"
    volumes:
      - pgdata:/var/lib/postgresql/data

  api:
    build:
      context: .
      dockerfile: Dockerfile
    container_name: geolocations-api
    environment:
      - ASPNETCORE_ENVIRONMENT=Development
      - ConnectionStrings__Default=Host=db.ibnkatceyebtnzndizdz.supabase.co;Database=postgres;Username=postgres;Password=cidax_pass;SSL Mode=Require;Trust Server Certificate=true
    ports:
      - "5000:80"
    depends_on:
      - db

volumes:
  pgdata: