//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Cidax.Exceptions {
    using System;
    
    
    /// <summary>
    ///   A strongly-typed resource class, for looking up localized strings, etc.
    /// </summary>
    // This class was auto-generated by the StronglyTypedResourceBuilder
    // class via a tool like ResGen or Visual Studio.
    // To add or remove a member, edit your .ResX file then rerun ResGen
    // with the /str option, or rebuild your VS project.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "17.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    public class ResourceMessagesException {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal ResourceMessagesException() {
        }
        
        /// <summary>
        ///   Returns the cached ResourceManager instance used by this class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("Cidax.Exceptions.ResourceMessagesException", typeof(ResourceMessagesException).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Overrides the current thread's CurrentUICulture property for all
        ///   resource lookups using this strongly typed resource class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to A categoria do local é obrigatória..
        /// </summary>
        public static string CATEGORY_NOT_EMPTY {
            get {
                return ResourceManager.GetString("CATEGORY_NOT_EMPTY", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to A categoria informada é inválida. Escolha uma das categorias permitidas..
        /// </summary>
        public static string INVALID_CATEGORY {
            get {
                return ResourceManager.GetString("INVALID_CATEGORY", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to A latitude deve estar entre -90 e 90 graus..
        /// </summary>
        public static string LATITUDE_INCLUSIVE_BETWEEN {
            get {
                return ResourceManager.GetString("LATITUDE_INCLUSIVE_BETWEEN", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to A latitude é obrigatória..
        /// </summary>
        public static string LATITUDE_NOT_EMPTY {
            get {
                return ResourceManager.GetString("LATITUDE_NOT_EMPTY", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to A longitude deve estar entre -180 e 180 graus..
        /// </summary>
        public static string LONGITUDE_INCLUSIVE_BETWEEN {
            get {
                return ResourceManager.GetString("LONGITUDE_INCLUSIVE_BETWEEN", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to A longitude é obrigatória..
        /// </summary>
        public static string LONGITUDE_NOT_EMPTY {
            get {
                return ResourceManager.GetString("LONGITUDE_NOT_EMPTY", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to O nome deve ter entre 3 e 100 caracteres..
        /// </summary>
        public static string NAME_LENGTH {
            get {
                return ResourceManager.GetString("NAME_LENGTH", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to O nome do local é obrigatório..
        /// </summary>
        public static string NAME_NOT_EMPTY {
            get {
                return ResourceManager.GetString("NAME_NOT_EMPTY", resourceCulture);
            }
        }
    }
}
